services:
  goapm-mysql:
    image: mysql:9.0.1
    container_name: goapm-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
      - ./volumes/mysql/logs:/var/log/mysql
    restart: always
  goapm-redis:
    image: redis:7.4.0
    container_name: goapm-redis
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis/data:/data
      - ./volumes/redis/logs:/var/log/redis
    restart: always
